// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "프로세스가 요청을 받을 수 있는지 확인하는 운영용 endpoint. DB 상태는 보지 않는다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "서버 상태",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/capabilities": {
            "get": {
                "description": "서버에 설정 · 구현된 로그인 provider. 인증이 비활성이면 503이다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "로그인 수단 목록",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.CapabilitiesResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/exchange": {
            "post": {
                "description": "콜백이 넘긴 result code를 앱 verifier · state와 함께 한 번만 세션으로 바꾼다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "로그인 결과 교환",
                "parameters": [
                    {
                        "description": "result code · 앱 PKCE verifier · 앱 state",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.ExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 · 틀린 proof · 만료 · 재사용 (invalid_callback)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 · OAuth 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/handoff/exchange": {
            "post": {
                "description": "web 서버가 verifier cookie와 코드로 앱 세션 아래 child web 세션을 받는다. 코드는 한 번만 쓸 수 있다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "handoff"
                ],
                "summary": "WebView 핸드오프 교환",
                "parameters": [
                    {
                        "description": "handoff 코드 · web verifier · next",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.HandoffExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 · 틀린 proof · 만료 · 재사용 · parent 취소 (invalid_callback)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/handoff/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "앱이 자기 Bearer로 WebView용 30초 일회용 코드를 받는다. root mobile 세션만 받는다.\nchallenge는 web 서버가 가진 verifier의 S256이고, next는 허용 목록(/ · /history) 안이어야 한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "handoff"
                ],
                "summary": "WebView 핸드오프 코드 발급",
                "parameters": [
                    {
                        "description": "web verifier의 challenge · 이동할 web 경로",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.HandoffStartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HandoffStartResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 · challenge · next (invalid_callback)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 무효 · root mobile 세션 아님 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "이 credential의 세션만 취소한다(root면 child 포함). 모르는 · 만료된 credential도 204다.",
                "tags": [
                    "auth"
                ],
                "summary": "로그아웃",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Authorization 헤더 형식 오류 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/oauth/callback": {
            "get": {
                "description": "provider가 브라우저를 돌려보내는 곳. 결과는 서버 설정의 앱 · web 복귀 URI로 302 redirect한다.\n성공이면 ` + "`" + `code` + "`" + `(60초 · 일회용 result code)와 앱 ` + "`" + `state` + "`" + `를, 실패면 ` + "`" + `error` + "`" + `(cancelled · provider_unavailable · invalid_callback)와 앱 ` + "`" + `state` + "`" + `를 query로 붙인다.\nprovider 토큰은 넘기지 않는다. transaction을 찾지 못하면 redirect하지 않고 400이다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "provider 콜백",
                "parameters": [
                    {
                        "type": "string",
                        "description": "서버가 만든 provider state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "provider authorization code",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "provider 오류 (예: access_denied)",
                        "name": "error",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "복귀 URI로 redirect",
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "복귀 URI ?code=\u0026state= 또는 ?error=\u0026state="
                            }
                        }
                    },
                    "400": {
                        "description": "모르는 · 이미 쓴 state (invalid_callback)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 · OAuth 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/oauth/cancel": {
            "post": {
                "description": "앱이 취소한 시작을 폐기한다. 본문이 잘못됐거나 모르는 state여도 204다.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "로그인 취소",
                "parameters": [
                    {
                        "description": "시작할 때 보낸 앱 state",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.OAuthCancelRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "503": {
                        "description": "인증 · OAuth 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/oauth/start": {
            "post": {
                "description": "앱 PKCE challenge · state로 OAuth transaction을 만들고 provider 동의 화면 주소를 돌려준다.\nGoogle state · PKCE verifier · nonce는 앱 값과 별개로 서버가 새로 만든다. 같은 앱 state는 한 번만 쓸 수 있다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "로그인 시작",
                "parameters": [
                    {
                        "description": "provider · 앱 challenge(S256) · 앱 state · platform",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.OAuthStartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.AuthorizeURLResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 · 미설정 provider · state 재사용 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 · OAuth 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/session": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Bearer credential의 세션을 확인하고 idle 만료를 연장한다. 만료 · 취소 · 모르는 credential은 401이다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "현재 세션",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.SessionResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/onboarding": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "내 온보딩 단계와 사용 목적. mobile과 web이 같은 진행에서 이어 간다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "온보딩 진행",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.OnboardingResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "단계(intro · purpose · first-image)와 사용 목적을 저장한다. 목적은 first-image에서만 있고 빈 목록은 건너뜀이다.\nunsure는 혼자만 고를 수 있다. 같은 단계를 다시 저장하거나 한 단계 앞으로만 갈 수 있고, 온보딩을 마친 뒤에는 바꿀 수 없다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "온보딩 진행 저장",
                "parameters": [
                    {
                        "description": "저장할 진행",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.OnboardingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.OnboardingResponse"
                        }
                    },
                    "400": {
                        "description": "계약 밖의 진행 (invalid_onboarding)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "이미 마친 온보딩 (onboarding_complete) · 건너뛰거나 되돌아가는 단계 (onboarding_out_of_order)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/onboarding/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "첫 사진 단계(first-image)에서 온보딩을 끝낸다. 본문은 없고 사용 목적은 바꾸지 않는다.\n이미 마쳤으면 그대로 성공한다 — 두 번 누르거나 다른 기기 · 탭이 먼저 마쳐도 오류가 아니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "온보딩 완료",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.OnboardingResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "첫 사진 단계 전 (onboarding_out_of_order)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/processing-jobs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "온보딩을 마친 뒤 올린 내 처리 작업을 최근에 만든 것부터 20개까지. 온보딩 첫 사진은 넣지 않는다.\n상태는 작업 조회와 같은 규칙이다. 끝나지 못해 실패로 보는 작업에는 finishedAt이 없다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "processing"
                ],
                "summary": "최근 사진 처리 작업",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ProcessingJobListResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "처리 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "사진 한 장(multipart 필드 image)으로 처리 작업을 만들고 바로 돌아온다. 결과는 작업 조회로 받는다.\nJPEG · PNG · GIF · WebP만 받고 7,500,000 byte까지다. 사진은 저장하지 않는다.\n온보딩을 마치기 전의 작업은 온보딩 첫 사진으로 남아 작업 목록에 나오지 않는다.\n모든 작업은 사진 유형(text · receipt)을 판단하고, 요청 시점에 저장된 처리 방식을 selection으로 남긴 뒤 실행해 outcome(processed)에 결과를 남긴다.\n지원하지 않는 사진 · 유형을 고를 수 없는 사진 · 읽을 글자가 없는 사진은 처리 방식을 실행하지 않고 outcome(unsupported · ambiguous)으로 끝난다.\n모델 호출이 실패하거나 응답이 계약 밖이면 작업은 failed다.\n처리 방식을 읽지 못하면 기본값으로 대신하지 않고 작업을 만들지 않는다(500).\n재처리: sourceJobId와 같은 사진을 다시 보낸다. 서버는 사진을 저장하지 않고 digest로 같은 사진인지만 본다.\n분류 · 유형 판단은 다시 하지 않고 원래 작업의 분류 결과를 쓴다. 저장된 처리 방식은 바꾸지 않는다.\n처리한 작업이면 action(같은 유형의 처리 방식)이 필수이고 imageType은 비우거나 원래 유형이다.\nambiguous 작업이면 imageType(후보 중 하나)이 필수이고, action을 비우면 그 유형에 저장된 처리 방식을 쓴다.\nunsupported · 실패 작업은 재처리할 수 없다. sourceJobId 없이 imageType · action을 보내면 400이다.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "processing"
                ],
                "summary": "사진 처리 시작",
                "parameters": [
                    {
                        "type": "file",
                        "description": "사진 한 장",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "재처리할 원래 작업",
                        "name": "sourceJobId",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "text",
                            "receipt"
                        ],
                        "type": "string",
                        "description": "재처리 유형",
                        "name": "imageType",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "extract_and_translate",
                            "extract_text",
                            "summarize",
                            "extract_and_summarize",
                            "record_expense"
                        ],
                        "type": "string",
                        "description": "재처리 처리 방식",
                        "name": "action",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ProcessingJobResponse"
                        }
                    },
                    "400": {
                        "description": "multipart가 아니거나 image 필드 없음 (invalid_image) · 원래 작업에 맞지 않는 유형 · 처리 방식 (invalid_reprocess)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "없는 · 다른 사용자의 원래 작업 (job_not_found)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "다른 사진 (image_mismatch) · 원래 작업이 처리 중 (source_running) · 재처리할 수 없는 원래 작업 (source_not_reprocessable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "상한 초과 (image_too_large)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "지원하지 않는 형식 (unsupported_image)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 · 처리 방식 조회 실패 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "처리 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/processing-jobs/{jobId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "내 처리 작업의 상태와, 완료됐다면 결과. 다른 사용자의 작업은 없는 작업과 같다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "processing"
                ],
                "summary": "사진 처리 작업",
                "parameters": [
                    {
                        "type": "string",
                        "description": "처리 시작이 돌려준 jobId",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ProcessingJobResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "없는 작업 (job_not_found)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "처리 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/processing-jobs/{jobId}/receipt-fields/{field}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "지출 정보 결과에서 필드 하나만 value로 확정하고 바뀐 뒤의 작업을 돌려준다. 다른 필드는 그대로다. 모델을 다시 부르지 않는다.\nvalue는 후보(candidates) 중 하나이거나 그 필드 형식의 직접 입력이다 — date: YYYY-MM-DD, total: 소수점 문자열(예: 12000, 12.50), currency: ISO 4217 코드, merchant · paymentMethod: 빈 문자열이 아닌 값.\n이미 같은 값으로 확정한 필드는 바꾸지 않고 200이다. 다른 값으로 확정한 필드는 409다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "processing"
                ],
                "summary": "영수증 필드 확정",
                "parameters": [
                    {
                        "type": "string",
                        "description": "처리 작업",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "merchant",
                            "date",
                            "total",
                            "currency",
                            "paymentMethod"
                        ],
                        "type": "string",
                        "description": "영수증 필드",
                        "name": "field",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "확정할 값",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.ReceiptFieldRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ProcessingJobResponse"
                        }
                    },
                    "400": {
                        "description": "없는 필드 · 형식이 틀린 값 · 본문 없음 (invalid_receipt_field)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "없는 · 다른 사용자의 작업 (job_not_found)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "지출 정보 결과가 없는 작업 (job_not_resolvable) · 다른 값으로 확정한 필드 (receipt_field_resolved)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "처리 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/processing-preferences": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "이미지 유형별 처리 방식. 고른 적이 없으면 서버 기본값(text: extract_and_translate, receipt: record_expense)이다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "preferences"
                ],
                "summary": "처리 방식",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ProcessingPreferencesResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/processing-preferences/{imageType}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "이미지 유형 하나의 처리 방식만 바꾸고, 바뀐 뒤의 전체를 돌려준다. 다른 유형의 값은 그대로다.\ntext: extract_and_translate · extract_text · summarize · extract_and_summarize\nreceipt: record_expense · extract_text · summarize",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "preferences"
                ],
                "summary": "처리 방식 변경",
                "parameters": [
                    {
                        "enum": [
                            "text",
                            "receipt"
                        ],
                        "type": "string",
                        "description": "이미지 유형",
                        "name": "imageType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "고른 처리 방식",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.ProcessingPreferenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ProcessingPreferencesResponse"
                        }
                    },
                    "400": {
                        "description": "모르는 유형 · 그 유형에 없는 처리 방식 (invalid_preference)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "credential 없음 · 만료 · 취소 (session_expired)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "내부 오류 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "인증 비활성 (provider_unavailable)",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpserver.AuthorizeURLResponse": {
            "type": "object",
            "properties": {
                "authorizeUrl": {
                    "type": "string",
                    "example": "https://accounts.google.com/o/oauth2/v2/auth?..."
                }
            }
        },
        "httpserver.CapabilitiesResponse": {
            "type": "object",
            "properties": {
                "providers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "google"
                    ]
                }
            }
        },
        "httpserver.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "enum": [
                        "session_expired",
                        "provider_unavailable",
                        "invalid_callback",
                        "invalid_image",
                        "image_too_large",
                        "unsupported_image",
                        "job_not_found",
                        "invalid_onboarding",
                        "onboarding_complete",
                        "onboarding_out_of_order",
                        "invalid_preference",
                        "invalid_reprocess",
                        "image_mismatch",
                        "source_running",
                        "source_not_reprocessable",
                        "invalid_receipt_field",
                        "job_not_resolvable",
                        "receipt_field_resolved"
                    ],
                    "example": "session_expired"
                }
            }
        },
        "httpserver.ExchangeRequest": {
            "type": "object",
            "required": [
                "code",
                "state",
                "verifier"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "one-time-result-code"
                },
                "state": {
                    "type": "string",
                    "example": "base64url-app-state-43-to-128-chars"
                },
                "verifier": {
                    "type": "string",
                    "example": "base64url-app-verifier-43-to-128-chars"
                }
            }
        },
        "httpserver.HandoffExchangeRequest": {
            "type": "object",
            "required": [
                "code",
                "next",
                "verifier"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "one-time-handoff-code"
                },
                "next": {
                    "type": "string",
                    "example": "/history/4f1c2a9e-0000-4000-8000-000000000000"
                },
                "verifier": {
                    "type": "string",
                    "example": "base64url-web-verifier-43-to-128-chars"
                }
            }
        },
        "httpserver.HandoffStartRequest": {
            "type": "object",
            "required": [
                "challenge",
                "next"
            ],
            "properties": {
                "challenge": {
                    "type": "string",
                    "example": "base64url-S256-challenge-of-the-web-verifier"
                },
                "next": {
                    "type": "string",
                    "example": "/history/4f1c2a9e-0000-4000-8000-000000000000"
                }
            }
        },
        "httpserver.HandoffStartResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "one-time-handoff-code"
                }
            }
        },
        "httpserver.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "httpserver.LoginResponse": {
            "type": "object",
            "properties": {
                "credential": {
                    "type": "string",
                    "example": "opaque-session-credential"
                },
                "session": {
                    "$ref": "#/definitions/httpserver.SessionResponse"
                }
            }
        },
        "httpserver.OAuthCancelRequest": {
            "type": "object",
            "required": [
                "state"
            ],
            "properties": {
                "state": {
                    "type": "string",
                    "example": "base64url-app-state-43-to-128-chars"
                }
            }
        },
        "httpserver.OAuthStartRequest": {
            "type": "object",
            "required": [
                "challenge",
                "platform",
                "provider",
                "state"
            ],
            "properties": {
                "challenge": {
                    "type": "string",
                    "example": "base64url-S256-challenge-of-the-app-verifier"
                },
                "platform": {
                    "type": "string",
                    "enum": [
                        "mobile",
                        "web"
                    ],
                    "example": "mobile"
                },
                "provider": {
                    "type": "string",
                    "example": "google"
                },
                "state": {
                    "type": "string",
                    "example": "base64url-app-state-43-to-128-chars"
                }
            }
        },
        "httpserver.OnboardingRequest": {
            "type": "object",
            "required": [
                "step"
            ],
            "properties": {
                "purposes": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "food",
                            "shopping",
                            "travel",
                            "events",
                            "receipt",
                            "foreign-language",
                            "work",
                            "unsure"
                        ]
                    },
                    "example": [
                        "food",
                        "receipt"
                    ]
                },
                "step": {
                    "type": "string",
                    "enum": [
                        "intro",
                        "purpose",
                        "first-image"
                    ],
                    "example": "first-image"
                }
            }
        },
        "httpserver.OnboardingResponse": {
            "type": "object",
            "properties": {
                "purposes": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "food",
                            "shopping",
                            "travel",
                            "events",
                            "receipt",
                            "foreign-language",
                            "work",
                            "unsure"
                        ]
                    },
                    "example": [
                        "food",
                        "receipt"
                    ]
                },
                "step": {
                    "type": "string",
                    "enum": [
                        "intro",
                        "purpose",
                        "first-image",
                        "complete"
                    ],
                    "example": "first-image"
                }
            }
        },
        "httpserver.ProcessingFactResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string",
                    "example": "날짜"
                },
                "value": {
                    "type": "string",
                    "example": "8월 20일 19시"
                }
            }
        },
        "httpserver.ProcessingJobListResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpserver.ProcessingJobSummaryResponse"
                    }
                }
            }
        },
        "httpserver.ProcessingJobResponse": {
            "type": "object",
            "properties": {
                "jobId": {
                    "type": "string",
                    "example": "4f1c2a9e-0000-4000-8000-000000000000"
                },
                "outcome": {
                    "$ref": "#/definitions/httpserver.ProcessingOutcomeResponse"
                },
                "result": {
                    "$ref": "#/definitions/httpserver.ProcessingResultResponse"
                },
                "selection": {
                    "$ref": "#/definitions/httpserver.ProcessingSelectionResponse"
                },
                "sourceJobId": {
                    "type": "string",
                    "example": "4f1c2a9e-0000-4000-8000-000000000001"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "running",
                        "completed",
                        "failed"
                    ],
                    "example": "running"
                }
            }
        },
        "httpserver.ProcessingJobSummaryResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-10-06T09:00:00Z"
                },
                "finishedAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-10-06T09:00:07Z"
                },
                "jobId": {
                    "type": "string",
                    "example": "4f1c2a9e-0000-4000-8000-000000000000"
                },
                "outcome": {
                    "$ref": "#/definitions/httpserver.ProcessingOutcomeResponse"
                },
                "result": {
                    "$ref": "#/definitions/httpserver.ProcessingResultResponse"
                },
                "selection": {
                    "$ref": "#/definitions/httpserver.ProcessingSelectionResponse"
                },
                "sourceJobId": {
                    "type": "string",
                    "example": "4f1c2a9e-0000-4000-8000-000000000001"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "running",
                        "completed",
                        "failed"
                    ],
                    "example": "completed"
                }
            }
        },
        "httpserver.ProcessingOutcomeResponse": {
            "type": "object",
            "properties": {
                "appliedAction": {
                    "type": "string",
                    "enum": [
                        "extract_and_translate",
                        "extract_text",
                        "summarize",
                        "extract_and_summarize",
                        "record_expense"
                    ],
                    "example": "extract_text"
                },
                "candidates": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "text",
                            "receipt"
                        ]
                    },
                    "example": [
                        "text",
                        "receipt"
                    ]
                },
                "imageType": {
                    "type": "string",
                    "enum": [
                        "text",
                        "receipt"
                    ],
                    "example": "text"
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "processed",
                        "unsupported",
                        "ambiguous"
                    ],
                    "example": "processed"
                },
                "output": {
                    "$ref": "#/definitions/httpserver.ProcessingOutputResponse"
                }
            }
        },
        "httpserver.ProcessingOutputResponse": {
            "type": "object",
            "properties": {
                "expense": {
                    "$ref": "#/definitions/httpserver.ReceiptExpenseResponse"
                },
                "original": {
                    "type": "string",
                    "example": "Open daily 9am-6pm"
                },
                "summary": {
                    "type": "string",
                    "example": "영업시간 안내"
                },
                "translation": {
                    "$ref": "#/definitions/httpserver.TranslationResponse"
                }
            }
        },
        "httpserver.ProcessingPreferenceRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "extract_and_translate",
                        "extract_text",
                        "summarize",
                        "extract_and_summarize",
                        "record_expense"
                    ],
                    "example": "summarize"
                }
            }
        },
        "httpserver.ProcessingPreferencesResponse": {
            "type": "object",
            "properties": {
                "receipt": {
                    "type": "string",
                    "enum": [
                        "record_expense",
                        "extract_text",
                        "summarize"
                    ],
                    "example": "record_expense"
                },
                "text": {
                    "type": "string",
                    "enum": [
                        "extract_and_translate",
                        "extract_text",
                        "summarize",
                        "extract_and_summarize"
                    ],
                    "example": "extract_and_translate"
                }
            }
        },
        "httpserver.ProcessingResultResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "enum": [
                        "place",
                        "event",
                        "receipt",
                        "foreign_text",
                        "shopping",
                        "work",
                        "other"
                    ],
                    "example": "event"
                },
                "confidence": {
                    "type": "string",
                    "enum": [
                        "high",
                        "medium",
                        "low"
                    ],
                    "example": "high"
                },
                "facts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpserver.ProcessingFactResponse"
                    }
                },
                "suggestedAction": {
                    "type": "string",
                    "enum": [
                        "save_place",
                        "add_to_calendar",
                        "record_expense",
                        "translate",
                        "none"
                    ],
                    "example": "add_to_calendar"
                }
            }
        },
        "httpserver.ProcessingSelectionResponse": {
            "type": "object",
            "properties": {
                "appliedAction": {
                    "type": "string",
                    "enum": [
                        "extract_and_translate",
                        "extract_text",
                        "summarize",
                        "extract_and_summarize",
                        "record_expense"
                    ],
                    "example": "extract_and_translate"
                },
                "imageType": {
                    "type": "string",
                    "enum": [
                        "text",
                        "receipt"
                    ],
                    "example": "text"
                }
            }
        },
        "httpserver.ReceiptExpenseResponse": {
            "type": "object",
            "properties": {
                "currency": {
                    "$ref": "#/definitions/httpserver.ReceiptFieldResponse"
                },
                "date": {
                    "$ref": "#/definitions/httpserver.ReceiptFieldResponse"
                },
                "merchant": {
                    "$ref": "#/definitions/httpserver.ReceiptFieldResponse"
                },
                "paymentMethod": {
                    "$ref": "#/definitions/httpserver.ReceiptFieldResponse"
                },
                "total": {
                    "$ref": "#/definitions/httpserver.ReceiptFieldResponse"
                }
            }
        },
        "httpserver.ReceiptFieldRequest": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "string",
                    "example": "12000"
                }
            }
        },
        "httpserver.ReceiptFieldResponse": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "12000",
                        "13000"
                    ]
                },
                "resolved": {
                    "type": "boolean",
                    "example": false
                },
                "value": {
                    "type": "string",
                    "example": "12000"
                }
            }
        },
        "httpserver.SessionResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-10-01T00:00:00Z"
                },
                "onboardingStep": {
                    "type": "string",
                    "enum": [
                        "intro",
                        "purpose",
                        "first-image",
                        "complete"
                    ],
                    "example": "intro"
                },
                "user": {
                    "$ref": "#/definitions/httpserver.UserResponse"
                }
            }
        },
        "httpserver.TranslationResponse": {
            "type": "object",
            "properties": {
                "needed": {
                    "type": "boolean",
                    "example": true
                },
                "text": {
                    "type": "string",
                    "example": "매일 오전 9시-오후 6시 영업"
                }
            }
        },
        "httpserver.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "4f1c2a9e-0000-4000-8000-000000000000"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer \u003copaque session credential\u003e\" 형식. 서버만 해석할 수 있는 세션 토큰.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "snapdone API",
	Description:      "snapdone Go API. 인증 credential은 JWT가 아닌 opaque 서버 세션 토큰.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
